### PR TITLE
html demo page

### PR DESCRIPTION
**Pull request by viebel**
First draft of a basic HTML demo page for running the closure compiler in the browser.

It would be nice to host the `jscomp.js` file somewhere (maybe on github pages?).

### CODE REVIEW

**Comment by MatrixFrog** [comment]
It sounds like this is similar to https://closure-compiler-debugger.appspot.com/gwt_debugger.html ?

**Comment by viebel** [comment]
Similar but not the same.
 I don't know how the compilation is running so fast there.

Also, how does it expose so many options?

**Comment by samthor** [comment]
That version actually uses GWT to build a web experience (i.e., with the checkboxes). The same version can't be used in Node or exported cleanly.

The reason it's so much faster is because it doesn't include [the default externs](https://closure-compiler.appspot.com/externs.js). Try adding that file to the externs textarea. 💣

I'm not against a demo script, but as I suggested in the bug, it should use web workers to keep the browser snappy.

**Comment by samthor** [comment]
I'll also add that if you don't need all the browser externs, you can specify `env: 'CUSTOM'`, which includes only the small set of language ones (needed for ES6). Builds speed up a lot.

**Comment by sherbondy** [comment]
Hey there, I actually tried making a revised version of the demo script that calls a WebWorker, but there appears to be a bug in the latest Chrome stable (55) where the call stack for WebWorkers is significantly smaller than the main JS context stack:
https://bugs.chromium.org/p/chromium/issues/detail?id=252492

This causes the worker process to crash with a RangeError on the very first line when it attempts to import jscomp.js:

```
Uncaught RangeError: Maximum call stack size exceeded
    at worker.js:1
```

It is supposedly fixed in Chrome 56, which is scheduled for release at the end of the month?

Here is a gist with the example code, confirmed to be working in Safari and Firefox but not Chrome:
https://gist.github.com/sherbondy/66dd2ba7500cf6b5d41203290228e699

**Pull request closed without merging**
