### PR TITLE
Update upstream GCC

### PR DESCRIPTION
**Pull request by gaearon**
I'm not sure what the policy is about upstream updates, but this is updating to GCC's current master. The tests pass (except for the one that's already failing on master):

screen shot 2017-11-13 at 1 50 18 pm

I want this so that we can unfork this package in React (currently had to fork to get https://github.com/google/closure-compiler/pull/2707 in).

If you'd like, I can also add docs for the new `renaming` option, now that it is available here.

### CODE REVIEW

**Comment by MatrixFrog** [comment]
Generally we only bump the version once a month when the other NPM package, and the Maven release, are updated, so that all three are in sync.

**Comment by gaearon** [comment]
Ah okay, thanks for explaining! Maybe worth noting as to a casual observer it's not clear if there is a schedule or it's done in an ad hoc way. But I understand this is probably not a priority 🙂

**Comment by gaearon** [comment]
>the other NPM package

Which npm package would that be?

>the Maven release

It seems like there were releases for October 23 and November 12: https://github.com/google/closure-compiler/wiki/Releases. My comment was on November 13, so there already has been a released by then.

Should I send another PR updating to that version?

**Comment by MatrixFrog** [comment]
If https://www.npmjs.com/package/google-closure-compiler-js is behind a version or two, then https://www.npmjs.com/package/google-closure-compiler should be up to date.

**Comment by MatrixFrog** [comment]
@brad4d should have the latest info on releases.

**Comment by brad4d** [comment]
FYI, I'm working on the December closure-compiler release this week, which includes updating this repo & corresponding npm.

**Comment by gaearon** [comment]
Sweet, thanks!

**Pull request closed without merging**
