### PR TITLE
Disable failing test

### PR DESCRIPTION
**Pull request by gaearon**
Not sure if this contribution even makes sense... 😛 but I've been looking at the repo, and figured maybe it's better to unbreak the CI so that any other potential PRs in the future can run on CI.

Feel free to close if that's nothing something you'd rather do.

### CODE REVIEW

**Comment by samthor** [comment]
So part of the reason I left this test failing is we hope to _fix_ it in the next release, and this is a good way to determine that we do (plus we've only had Travis CI set up for the last month or so).

If you're interested in local dev, could you just comment this out in your own branch for a Travis test, or work around it some other way? I'm happy to be convinced otherwise, btw.

**Comment by MatrixFrog** [comment]
@samthor I think you know how to fix it right? Can you either do the fix yourself, or give us a hint of where to start? I share your concern that if we disable it now we can easily forget about it indefinitely and forget to ever go back and fix it, so if we can get it fixed soon-ish that would be ideal.

**Comment by gaearon** [comment]
Do I understand correctly updating underlying GCC would fix this?

**Comment by gaearon** [comment]
It seems like it doesn't. So this is a bug in this package, and not in the upstream GCC?

**Comment by ChadKillingsworth** [comment]
this was fixed upstream

**Pull request closed without merging**
